### PR TITLE
Add yaml support - closes #2

### LINKED ISSUE #2: Support YAML config file sources
Could use the official Dart YAML parser: https://pub.dev/packages/yaml
File parsing is currently located in `_resolveConfig`: https://github.com/Francessco121/dart-embedded-config/blob/master/embedded_config/lib/src/config_generator.dart#L139

- [ ] Update `ConfigGenerator` to parse files as YAML with `.yaml` and `.yml` extensions.
- [ ] Update documentation to say both JSON and YAML are supported.

### PR DESCRIPTION
**Pull request by halkeye**
Could absolutely use more tests, but the basics seem to work

### CODE REVIEW

**Comment by Francessco121** [comment]
Thanks so much! I'll take a look at this soon.

**Review by Francessco121 — APPROVED** [review]
Looks good! There is a small bug preventing nested configs from working, but I have a fix that I'll just commit after, no need to worry.

**Comment by halkeye** [comment]
oh awesome. Can you tag me in your fix? I'd like to see what broke.

I'm pretty new to this and just poking around with what I can do.

**Comment by Francessco121** [comment]
@halkeye The issue is that `YamlMap`s are typed as `Map<dynamic, dynamic>` but the config gen code assumes it's `<String, dynamic>`. You had the correct cast for the initial document load, but nested maps also have this issue. I just added the extra cast plus some code to explicitly reject non-string keys (since YAML can have pretty much anything as a key). https://github.com/Francessco121/dart-embedded-config/commit/dad72294de5870c66ffc3f8d87dd2735343906e3#diff-2105c4596bbad10bf135721b595f67ebecc726cbf4d338a73709d217d353840eL188-L190

No worries tho! 🙂

**Pull request merged**
